module.exports = {
  formHead: {
    fontSize: 30,
    color: "black",
    textAlign: "center",
    fontWeight: "bold",
    marginBottom: 40,
  },
  formInput: {
    width: "80%",
    color: "black",
    fontWeight: "bold",
    backgroundColor: "gray",
    borderRadius: 20,
    marginVertical: 10,
    paddingHorizontal: 15,
    paddingVertical: 10,
    fontSize: 18,
  },
  formButton: {
    width: "80%",
    backgroundColor: "black",
    borderRadius: 40,
    borderColor: "black",
    borderWidth: 1,
    fontSize: 25,
    color: "white",
    textAlign: "center",
    paddingVertical: 10,
    marginVertical: 10,
  },
  formTextLinkRight: {
    fontSize: 15,
    color: "gray",
    textAlign: "right",
    width: "80%",
    marginVertical: 10,
  },
  formTextLinkLeft: {
    fontSize: 20,
    fontWeight: "bold",
    color: "black",
    textAlign: "left",
    width: "80%",
    marginVertical: 30,
  },
  formTextLinkCenter: {
    color: "black",
    fontSize: 16,
  },
  formHead2: {
    fontSize: 20,
    color: "black",
    textAlign: "center",
  },
  formHead3: {
    fontSize: 20,
    color: "black",
    fontWeight: "400",
    padding: 10,
    borderRadius: 10,
    textAlign: "center",
    width: "80%",
    marginVertical: 10,
  },
};
